---
ansible_host: 192.168.56.11
ansible_user: dummy
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33316631366532643461326631626635633364343966633539646532346464316137616530386535
          6330643466323832366332633764303130346330626636630a316366343764613231666136616363
          39306338393864396265613033373461353436343763316331316436343662313766346236383837
          3431616363393435660a623235346132373733303434663134313831353932353235333137626335
          6537
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63346130613331653162373339383666333533393234643264623330373131373765326263623563
          6536383265346165643562363965383265353662393464640a343233356331653933346362656434
          39613638383065323132323635663233663662383432363465326261383430356239356332656434
          3031373063386662330a633130373435353736313137636466626364643935623566393337396334
          3864

# Vaultwarden Secrets (Encrypted)
vaultwarden_admin_token: "$argon2id$v=19$m=19456,t=2,p=1$Y0pWQmZsS1hmdlR1dVkrSHNSK1ZQeEdmOTdiUEtqZUlEcW5LaHg3Sjhucz0$+LlQXosldfAJ19YnnfMAGOY3WAMxWuN4ClHB7JAUEhE"
vaultwarden_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64376238363436366438633737343964623861323566623864366139393065313665626136313734
          3730363134313734373032636631346632366537376162340a613137393731356436636164633736
          63613461343638306431366536393835643132653831366364316237323939633965646662323532
          3263363465333666340a313036326432663436373466663164393762303939653861353332623839
          3632

# Vaultwarden data and configuration directories
vaultwarden_data_dir: "./data"
postgres_data_dir: "./postgres"
vaultwarden_backup_dir: "./"

# Kopia variables
kopia_backup_data_dir: "/data"