# https://kopia.io/docs/installation/#docker-images
# https://github.com/kopia/kopia/blob/master/tools/docker/docker-compose.yml
# Multiple repos: https://github.com/kopia/kopia/issues/2976

services:
  kopia:
    # https://hub.docker.com/r/kopia/kopia/tags
    image: kopia/kopia:0.19.0
    hostname: kopia
    container_name: kopia
    cap_add:
      - SYS_ADMIN # Required for FUSE mounts (e.g., browsing snapshots)
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
      # - KOPIA_HTTPS=true # Optional
      # - REFRESH_INTERVAL= # Optional
    # https://github.com/kopia/kopia/blob/master/tools/docker/Dockerfile
    entrypoint: 
      - /bin/bash
      - -c
      - |
        export KOPIA_UI_USERNAME=$$(cat /run/secrets/kopia_username)
        export KOPIA_UI_PASSWORD=$$(cat /run/secrets/kopia_password)
        export KOPIA_PASSWORD=$$(cat /run/secrets/kopia_repo_password)
        exec /bin/kopia server start --disable-csrf-token-checks --insecure --address=0.0.0.0:51515 --server-username=$$KOPIA_UI_USERNAME --server-password=$$KOPIA_UI_PASSWORD
    volumes:
      # Mount local folders needed by kopia
      - ./config:/app/config
      - ./cache:/app/cache
      - ./logs:/app/logs
      # Source path being snapshotted (read-only)
      - /:/data:ro
      # Backup repositories (where snapshotted backup stored)
      - ./repository:/repository # Optional: Use if repository is stored locally
      # Temporary directory for snapshot browsing via FUSE mounts.
      # The ':shared' propagation makes snapshot mounts created *inside* the container
      # (within /tmp) visible and accessible on the *host* system at /tmp.
      # Remove ':shared' if you do not need to browse FUSE mounts directly from the host.
      - /tmp:/tmp:shared # Optional: Required for host visibility of FUSE mounts
    devices:
      - /dev/fuse:/dev/fuse:rwm # Required for FUSE mounts
    secrets:
      - kopia_username
      - kopia_password
      - kopia_repo_password
    # ports:
    #   - 51515:51515 # Exposed via Traefik instead
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.kopia.loadbalancer.server.port=51515"
      ## Router
      ### Private
      - "traefik.http.routers.kopia-local.rule=Host(`kopia.yourdomain.local`)"
      - "traefik.http.routers.kopia-local.entrypoints=websecure"
      - "traefik.http.routers.kopia-local.tls.certresolver=stepca"
      
secrets:
  kopia_username:
    file: ./secrets/kopia_username
  kopia_password:
    file: ./secrets/kopia_password
  kopia_repo_password:
    file: ./secrets/kopia_repo_password
    
networks:
  proxy:
    external: true