# https://thedxt.ca/2022/10/cloudflare-tunnel-with-docker/

services:
  cloudflared-tunnel:
    container_name: cloudflared-tunnel
    # https://hub.docker.com/r/cloudflare/cloudflared/tags
    image: cloudflare/cloudflared:2025.1.0-amd64
    restart: always
    volumes:
      - <PATH_TO_CONFIG_FOLDER>:/home/nonroot/.cloudflared/
    command: tunnel --config /home/nonroot/.cloudflared/config.yaml run
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true