all:
  children:
    ubuntu_servers:
      hosts:
        server1:
          ansible_host: server1.example.com
          ansible_user: admin1
        server2:
          ansible_host: server2.example.com
          ansible_user: admin2