---
ansible_host: 192.168.56.11
ansible_user: dummy
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33316631366532643461326631626635633364343966633539646532346464316137616530386535
          6330643466323832366332633764303130346330626636630a316366343764613231666136616363
          39306338393864396265613033373461353436343763316331316436343662313766346236383837
          3431616363393435660a623235346132373733303434663134313831353932353235333137626335
          6537
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63346130613331653162373339383666333533393234643264623330373131373765326263623563
          6536383265346165643562363965383265353662393464640a343233356331653933346362656434
          39613638383065323132323635663233663662383432363465326261383430356239356332656434
          3031373063386662330a633130373435353736313137636466626364643935623566393337396334
          3864

# Keycloak Secrets (Encrypted)
keycloak_admin_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66663864386231383234383839343039383037393533393233613537656263303337613366343236
          6664383834376431313938626334363865663331633562370a616633616530613632366363636362
          64353838363930626137366235386561616664386662343934393632633666643262343761386161
          6236353130633161640a323735376433613038393464306633356339383566613931663762653632
          3837
keycloak_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30346238353233313163313065326631346339396663386133303664653664386535343362343830
          3138323034363533383330343262376236373837353536330a343436346438353061323362633036
          62653830383165363263353766356131633832616537636664653832623862616265343834303130
          3061346463616330610a366136346339616531343038303265393536303630626663666531396434
          3034
keycloak_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64376238363436366438633737343964623861323566623864366139393065313665626136313734
          3730363134313734373032636631346632366537376162340a613137393731356436636164633736
          63613461343638306431366536393835643132653831366364316237323939633965646662323532
          3263363465333666340a313036326432663436373466663164393762303939653861353332623839
          3632

# Keycloak data and configuration directories
keycloak_postgres_data_dir: "./postgres"
keycloak_backup_dir: "./"

# Kopia variables
kopia_backup_data_dir: "/data"