ansible_user: vagrant
ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
ansible_python_interpreter: /usr/bin/python3

kopia_repo_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32633030356234326562643139663766613038363163336531633938626131336339363461396533
          3738636339383163633530613865363432373561613761370a616363386536656435646339303637
          31396433386563656462316431386231393937353034373231656434646135653737393239383062
          3133333539663862340a356464663737653731383461353937333834393039323230633133626135
          6265