# https://dozzle.dev/guide/getting-started#running-with-docker

services:
  dozzle:
    # https://hub.docker.com/r/amir20/dozzle/tags
    image: amir20/dozzle:v8.7.2
    container_name: dozzle
    environment:
      DOZZLE_HOSTNAME: dozzle
      DOZZLE_REMOTE_AGENT: agent_ip:7007
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle-local.rule=Host(`dozzle.yourdomain.local`)"
      - "traefik.http.routers.dozzle-local.entrypoints=websecure"
      - "traefik.http.routers.dozzle-local.tls.certresolver=stepca"
      - "traefik.http.routers.dozzle-local.middlewares=oauth2-admin@file"
    # https://dozzle.dev/guide/healthcheck
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped

networks:
  proxy:
    external: true
