services:
  agent:
    container_name: portainer_agent
    image: 'portainer/agent:linux-amd64-2.20.3-alpine'
    restart: unless-stopped
    ports:
      - '9001:9001'
    volumes:
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
      - '/var/run/docker.sock:/var/run/docker.sock'
    network_mode: host
