ansible_user: vagrant
ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
ansible_python_interpreter: /usr/bin/python3

forgejo_admin_username: forgejo_admin
forgejo_admin_email: forgejo@example.com
forgejo_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34393535343930623931666132303739373930653962306133366666363937343164613837323633
          3339393930343461613365636663303035316238366135610a343365633337386537366333303264
          37636335303134353237646439653131396461623161316339303061356563653266663566323732
          3133643939306661320a343037643061333532306437366634663932323966623064373631633036
          62333534363961343032633634396232323164336234653831303037393435666333

db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38313966656539636366313662343034343732376464303665376130353336313361316438663961
          3363366363616264623436326462356461633865383564610a626538346239316565323864353339
          66306638303235643334626330313065393666383666366238633762646564386664356439373962
          3933346138666664360a333663353465343137363732376664356663383534326261373638633163
          66373434623463613762333438303331393138343732393462616538363138373761343234383035
          35383337323735323061333037306233663533643631633664613835303437343232633266613638
          65316366363233373963636662383364613030653739386234653037303332396337386631316134
          38616135333961386633