ansible_user: vagrant
ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
ansible_python_interpreter: /usr/bin/python3

db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38313966656539636366313662343034343732376464303665376130353336313361316438663961
          3363366363616264623436326462356461633865383564610a626538346239316565323864353339
          66306638303235643334626330313065393666383666366238633762646564386664356439373962
          3933346138666664360a333663353465343137363732376664356663383534326261373638633163
          66373434623463613762333438303331393138343732393462616538363138373761343234383035
          35383337323735323061333037306233663533643631633664613835303437343232633266613638
          65316366363233373963636662383364613030653739386234653037303332396337386631316134
          38616135333961386633