---
all:
  children:
    managers:
      hosts:
        ubuntu1:
          ansible_host: 192.168.56.11
    agents:
      hosts:
        ubuntu2:
          ansible_host: 192.168.56.12
        ubuntu3:
          ansible_host: 192.168.56.13