# https://github.com/AdguardTeam/AdGuardHome/wiki/Docker

services:
  adguardhome:
    container_name: adguardhome
    hostname: 'adguardhome'
    # https://hub.docker.com/r/adguard/adguardhome/tags
    image: adguard/adguardhome:v0.107.54
    restart: unless-stopped
    ports:
      #   - '3000:3000/tcp'
      #   - '443:443/udp'
      #   - '443:443/tcp'
      #   - '80:80/tcp'
      #   # Debugging profiles
      #   - '6060:6060/tcp'
      #   # DCHP ports
      #   - '68:68/tcp'
      #   - '68:68/udp'
      #   - '67:67/udp'
      #   ###
      #   # region DNS ports
      # plan DSN
      - '53:53/udp'
      - '53:53/tcp'
      #   # DNSSEC
      #   - '5443:5443/udp'
      #   - '5443:5443/tcp'
      #   - '853:853/udp'
      #   - '853:853/tcp'
      #   # endregion DNS ports
    volumes:
      - 'adguardhome_conf:/opt/adguardhome/conf'
      - 'adguardhome_work:/opt/adguardhome/work'
    networks:
      openwrt_vlan:
        ipv4_address: 10.10.10.10

volumes:
  adguardhome_conf:
    driver: local
  adguardhome_work:
    driver: local

networks:
  openwrt_vlan:
    external: true
