# https://tailscale.com/blog/docker-tailscale-guide
# https://gist.github.com/bnhf/fed4cc3035f32a0f086b1da074a3d50b

services:
  tailscale:
    image: tailscale/tailscale:v1.70.0
    container_name: tailscale
    hostname: tailscale
    restart: unless-stopped
    volumes:
      - tailscale-state:/var/lib/tailscale
      # NOTE: enable access to tun for LXC containers
      # https://tailscale.com/kb/1130/lxc-unprivileged
      - /dev/net/tun:/dev/net/tun
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      # TS_EXTRA_ARGS: "--advertise-tags=tag:container --reset"
      TS_EXTRA_ARGS: "--accept-routes --advertise-tags=tag:container --reset"
      TS_STATE_DIR: /var/lib/tailscale
      TS_ROUTES: ${TS_ROUTES}
      TS_USERSPACE: false
    cap_add:
      - net_admin
      - sys_module
    # NOTE: for tailscale enable ip forwarding
    privileged: true
    networks:
      openwrt_vlan:
        ipv4_address: 10.10.10.6

networks:
  openwrt_vlan:
    external: true

volumes:
  tailscale-state:
    driver: local
