---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-utils
    state: present
    update_cache: true

- name: Enable unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    enabled: true
    state: started

- name: Install notification script
  ansible.builtin.template:
    src: unattended-upgrades-notify.sh.j2
    dest: /usr/local/bin/unattended-upgrades-notify.sh
    owner: root
    group: root
    mode: "0755"

- name: Install notification path unit
  ansible.builtin.template:
    src: unattended-upgrades-notify.path.j2
    dest: /etc/systemd/system/unattended-upgrades-notify.path
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd

- name: Install notification service unit
  ansible.builtin.template:
    src: unattended-upgrades-notify-service.j2
    dest: /etc/systemd/system/unattended-upgrades-notify.service
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd

- name: Enable and start notification path unit
  ansible.builtin.systemd:
    name: unattended-upgrades-notify.path
    enabled: true
    state: started
    daemon_reload: true
