---
- name: Install required packages
  apt:
    name: 
      - unattended-upgrades
      - apt-utils
    state: present
    update_cache: yes

- name: Enable unattended-upgrades
  service:
    name: unattended-upgrades
    enabled: yes
    state: started

- name: Install notification script
  template:
    src: unattended-upgrades-notify.sh.j2
    dest: /usr/local/bin/unattended-upgrades-notify.sh
    owner: root
    group: root
    mode: 0755

- name: Install notification path unit
  template:
    src: unattended-upgrades-notify.path.j2
    dest: /etc/systemd/system/unattended-upgrades-notify.path
    owner: root
    group: root
    mode: 0644
  notify: reload systemd

- name: Install notification service unit
  template:
    src: unattended-upgrades-notify-service.j2
    dest: /etc/systemd/system/unattended-upgrades-notify.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd

- name: Enable and start notification path unit
  systemd:
    name: unattended-upgrades-notify.path
    enabled: yes
    state: started
    daemon_reload: yes
