---
ansible_host: 192.168.56.11
ansible_user: dummy
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33316631366532643461326631626635633364343966633539646532346464316137616530386535
          6330643466323832366332633764303130346330626636630a316366343764613231666136616363
          39306338393864396265613033373461353436343763316331316436343662313766346236383837
          3431616363393435660a623235346132373733303434663134313831353932353235333137626335
          6537
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63346130613331653162373339383666333533393234643264623330373131373765326263623563
          6536383265346165643562363965383265353662393464640a343233356331653933346362656434
          39613638383065323132323635663233663662383432363465326261383430356239356332656434
          3031373063386662330a633130373435353736313137636466626364643935623566393337396334
          3864

# Host-specific Docker macvlan configurations for ubuntu1
docker_macvlan_setups:
  - file_name: "general_lan"
    parent_interface: "enp0s8" # Assumed to be the Vagrant private network interface
    host_ip: "192.168.56.11"
    macvlan_interface_name: "mv-genlan"
    container_cidrs:
      - "192.168.56.96/28" # Range: 192.168.56.96 - 192.168.56.111 (gateway .97, broadcast .111, usable .100-.110)
