ansible_host: 192.168.56.11

# Glance data and configuration directories
glance_config_dir: "./config"
glance_assets_dir: "./assets"

# Glance secret token
glance_secret_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63373336393333306664666664653535343338306236343935326366326237653038666232353433
          6536383337373737396466323930336135653662663434610a313138393030323637613137383962
          63613835333762653936326665313030306261363362343330626666326431306434333835316636
          3235643266323662320a326539383664386261323862336364393031376639323130303135653961
          65326535356535333030396438363930666637313933633365656539666530633761393835303037
          3361383164646461666132616331613539393830393932633737