all:
  children:
    ubuntu_servers:
      hosts:
        server1:
          ansible_host: server1.example.com
          ansible_user: admin1
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        server2:
          ansible_host: server2.example.com
          ansible_user: admin2
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
