all:
  children:
    ubuntu_servers:
      hosts:
        ubuntu1:
          ansible_host: 192.168.56.11
        ubuntu2:
          ansible_host: 192.168.56.12
      vars:
        ansible_user: vagrant
        ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        ansible_python_interpreter: /usr/bin/python3