all:
  children:
    ubuntu_servers:
      hosts:
        ubuntu1:
          ansible_host: 192.168.56.11
          ansible_user: ansible1
          ansible_ssh_pass: password1
          ansible_sudo_pass: password1
        ubuntu2:
          ansible_host: 192.168.56.12
          ansible_user: ansible2
          ansible_ssh_pass: password2
          ansible_sudo_pass: password2
      vars:
        ansible_python_interpreter: /usr/bin/python3
