---
- name: Include check mount tasks
  ansible.builtin.include_tasks: check_mount.yml

- name: Include mount share tasks
  ansible.builtin.include_tasks: mount_share.yml
  when: operation_mode == 'mount'

- name: Include test mount tasks
  ansible.builtin.include_tasks: test_mount.yml
  when: operation_mode == 'test'
