# https://miniflux.app/docs/docker.html#docker-compose

services:
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:2.1.4-distroless
    restart: unless-stopped
    # ports:
    #   - "80:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@10.10.10.13/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
    networks:
      openwrt_vlan:
        ipv4_address: 10.10.10.12

  db:
    container_name: miniflux-db
    image: postgres:15.7-bookworm
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "miniflux" ]
      interval: 10s
      start_period: 30s
    networks:
      openwrt_vlan:
        ipv4_address: 10.10.10.13

volumes:
  miniflux-db:
    driver: local

networks:
  openwrt_vlan:
    external: true
