---
ansible_user: vagrant
ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
ansible_python_interpreter: /usr/bin/python3

# Make sure Headscale service is set up
headscale_url: "http://192.168.56.10:8080"