---
healthchecks_base_url: "https://healthchecks.yourdomain"
healthchecks_uuid: ""
gotify_url: "https://gotify.yourdomain"  # Replace with your Gotify server URL
gotify_token: ""  # Add your Gotify application token here
gotify_priority: 5  # Notification priority (1-10)

apt_upgrade_days: "Sun,Sat"
apt_upgrade_time: "02:00:00"
timezone: "Asia/Tokyo"