# https://docs.portainer.io/start/install-ce/server/docker/linux

services:
  portainer:
    container_name: portainer
    # https://hub.docker.com/r/portainer/portainer-ce/tags
    image: portainer/portainer-ce:2.27.1-alpine
    restart: unless-stopped
    # ports:
    #  - "9443:9443"
    #  - "8000:8000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    # https://docs.portainer.io/advanced/reverse-proxy/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer-local.rule=Host(`portainer.yourdomain`)"
      - "traefik.http.routers.portainer-local.entrypoints=websecure"
      - "traefik.http.routers.portainer-local.service=portainer-local"
      - "traefik.http.routers.portainer-local.tls.certresolver=stepca"

networks:
  proxy:
    external: true

volumes:
  portainer_data:
    external: true
