ansible_python_interpreter: /usr/bin/python3

use_docker: true

# Traefik configuration
use_traefik: true

# Router configuration
use_traefik_router_private: true
use_traefik_router_public: true

# Service name (will be used as subdomain)
service_name: "beszel"

public_apex_domain: "yourdomain"
private_apex_domain: "yourdomain.local"