# https://miniflux.app/docs/docker.html#docker-compose

services:
  miniflux:
    container_name: miniflux
    image: miniflux/miniflux:2.1.4-distroless
    restart: unless-stopped
    # ports:
    #   - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@10.10.10.13/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=test123
    networks:
      - miniflux
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.miniflux.loadbalancer.server.port=8080"
      - "traefik.http.routers.miniflux-local.rule=Host(`miniflux.yourdomain.local`)"
      - "traefik.http.routers.miniflux-local.entrypoints=websecure"
      - "traefik.http.routers.miniflux-local.tls.certresolver=stepca"

  db:
    container_name: miniflux-db
    # https://hub.docker.com/_/postgres/tags
    image: postgres:16.5-alpine3.20
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_DB=miniflux
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    secrets:
      - db_password
    networks:
      - miniflux
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "miniflux" ]
      interval: 10s
      start_period: 30s

volumes:
  miniflux-db:
    driver: local
    
networks:
  miniflux:
    driver: bridge
  proxy:
    external: true

secrets:
  db_password:
    file: ./secrets/db_password