# https://docs.portainer.io/admin/environments/add/docker/agent

services:
  portainer_agent:
    container_name: portainer_agent
    # https://hub.docker.com/r/portainer/agent/tags
    image: 'portainer/agent:2.24.0-alpine'
    restart: always
    volumes:
      - '/:/host'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '9001:9001'
