http:
  routers:
    pve-local-router:
      rule: Host(`pve.yourdomain.local`)
      service: pve-local-service
      entryPoints:
        - "websecure"
      tls:
        certResolver: stepca

  services:
    pve-local-service:
      loadBalancer:
        servers:
          - url: "https://192.168.1.150:8006"
