http:
  routers:
    pve-local:
      rule: Host(`pve.yourdomain.local`)
      service: pve
      entryPoints:
        - "websecure"
      tls:
        certResolver: stepca

  services:
    pve:
      loadBalancer:
        # https://doc.traefik.io/traefik/v3.2/routing/services/#serverstransport
        serversTransport: pve
        servers:
          - url: "https://192.168.xxx.xxx:8006"

  # https://doc.traefik.io/traefik/v3.2/routing/services/#insecureskipverify
  serversTransports:
    pve:
      insecureSkipVerify: true
