version: '3.9'
services:
  unbound:
    container_name: my-unbound
    image: 'mvance/unbound:1.20.0'
    restart: unless-stopped
    ports:
      - '53:53/udp'
      - '53:53/tcp'
    volumes:
      - '/my-directory/unbound:/opt/unbound/etc/unbound/'
    network:
      - proxy

networks:
  proxy:
    external: true