services:
  app:
    container_name: teleport
    image: public.ecr.aws/gravitational/teleport-distroless-debug:16.1.1
    restart: unless-stopped
    ports:
      - "3080:3080"
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
    volumes:
      - /root/teleport/config:/etc/teleport
      - teleport_data:/data
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true

volumes:
  teleport_data:
    driver: local
