ansible_host: 192.168.56.10

# Headplane data and configuration directories
headplane_config_path: "./config.yml"
headplane_data_dir: "./headplane-data"

# Headscale data and configuration directories
headscale_config_dir: "./headscale-config"
headscale_data_dir: "./headscale-data"

# Ensure that this is exactly 32 characters long
# Example generation Linux command: openssl rand -base64 24 | tr -d '\n'
headplane_cookie_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38633762333163313266643064353536313833363736333135613064633130666134383636353139
          3465633732376535386165613736353465333339346662610a323062663066316330396265393139
          31633934643133316565356364633837623536383930643039303034363530656535633665363565
          3266663431346633610a643064643131663033333166346230626437366361373963626162393638
          35313433376133386135323937666662653535656661623433663564316335363039316230386530
          3565386263303736303966363231376161336162653865386333