ansible_host: 192.168.56.10

# Headplane data and configuration directories
headplane_config_path: "./config.yml"
headplane_data_dir: "./headplane-data"

# Headscale data and configuration directories
headscale_config_dir: "./headscale-config"
headscale_data_dir: "./headscale-data"

# Ensure that this is exactly 32 characters long
# Example generation Linux command: "head -c32 /dev/urandom | base64"
headplane_cookie_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66643731663265303532613134356362643139623165646437353162663866373130333736353866
          3862633131373732363639326163333533663230366164380a396337653161383931623339336362
          32656337386539663433383562373662363762623133326237333333346437393838663632316465
          6137363765336331660a383136313038663334346664646266333338623837663164633432303432
          66646435333436376438366234336534333639373635613965363363343935373431306464666236
          6131653934383735393365666338373262326364393937343662