# https://dozzle.dev/guide/agent#setting-up-healthcheck

services:
  dozzle-agent:
    # https://hub.docker.com/r/amir20/dozzle/tags
    image: amir20/dozzle:v8.9.0
    container_name: dozzle-agent
    restart: unless-stopped
    command: agent
    environment:
      DOZZLE_HOSTNAME: dozzle-agent
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 7007:7007
