---
ansible_host: 192.168.56.11
ansible_user: dummy
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33316631366532643461326631626635633364343966633539646532346464316137616530386535
          6330643466323832366332633764303130346330626636630a316366343764613231666136616363
          39306338393864396265613033373461353436343763316331316436343662313766346236383837
          3431616363393435660a623235346132373733303434663134313831353932353235333137626335
          6537
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63346130613331653162373339383666333533393234643264623330373131373765326263623563
          6536383265346165643562363965383265353662393464640a343233356331653933346362656434
          39613638383065323132323635663233663662383432363465326261383430356239356332656434
          3031373063386662330a633130373435353736313137636466626364643935623566393337396334
          3864

kopia_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32633030356234326562643139663766613038363163336531633938626131336339363461396533
          3738636339383163633530613865363432373561613761370a616363386536656435646339303637
          31396433386563656462316431386231393937353034373231656434646135653737393239383062
          3133333539663862340a356464663737653731383461353937333834393039323230633133626135
          6265
kopia_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32633030356234326562643139663766613038363163336531633938626131336339363461396533
          3738636339383163633530613865363432373561613761370a616363386536656435646339303637
          31396433386563656462316431386231393937353034373231656434646135653737393239383062
          3133333539663862340a356464663737653731383461353937333834393039323230633133626135
          6265
kopia_repo_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32633030356234326562643139663766613038363163336531633938626131336339363461396533
          3738636339383163633530613865363432373561613761370a616363386536656435646339303637
          31396433386563656462316431386231393937353034373231656434646135653737393239383062
          3133333539663862340a356464663737653731383461353937333834393039323230633133626135
          6265

# Kopia data and configuration directories
kopia_config_dir: "./config"
kopia_cache_dir: "./cache"
kopia_logs_dir: "./logs"
kopia_repository_dir: "/mnt/test/kopia/repository"