server:
  # https://github.com/glanceapp/glance/blob/main/docs/configuration.md#assets-path
  assets-path: /app/assets

# https://github.com/glanceapp/glance/blob/main/docs/themes.md
theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65

pages:
  - name: Dashboard
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      # Left Column
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
          - type: calendar
            first-day-of-week: sunday
          - type: weather
            location: Fukuoka, Japan

      # Right Column (takes remaining space)
      - size: full
        widgets:
          - type: monitor
            title: Services
            cache: 1m
            sites:
              - title: Nextcloud
                url: "https://github.com/nextcloud/server"
                icon: di:nextcloud
              - title: Forgejo
                url: "https://codeberg.org/forgejo/forgejo"
                icon: di:forgejo
              - title: Vaultwarden
                url: "https://github.com/dani-garcia/vaultwarden"
                icon: di:vaultwarden
              - title: IT Tools
                url: "https://github.com/CorentinTh/it-tools"
                icon: /assets/icons/it-tools.png
              - title: Omni Tools
                url: https://github.com/iib0011/omni-tools
                icon: /assets/icons/omni-tools.svg
              - title: Hedgedoc
                url: "https://github.com/hedgedoc/hedgedoc"
                icon: /assets/icons/hedgedoc.png
              - title: Open WebUI
                url: "https://github.com/open-webui/open-webui"
                icon: /assets/icons/open-webui.png
          - type: monitor
            title: Monitoring
            cache: 1m
            sites:
              - title: Beszel
                url: "https://github.com/henrygd/beszel"
                icon: /assets/icons/beszel.png
              - title: Dozzle
                url: "https://github.com/amir20/dozzle"
                icon: di:dozzle
              - title: Uptime Kuma
                url: "https://github.com/louislam/uptime-kuma"
                icon: /assets/icons/uptime-kuma.png
              - title: Gotify
                url: "https://github.com/gotify/server"
                icon: di:gotify
              - title: GoAcess
                url: "https://github.com/xavier-hernandez/goaccess-for-nginxproxymanager"
                icon: /assets/icons/goaccess.svg
          - type: monitor
            title: Server Management
            cache: 1m
            sites:
              - title: Proxmox
                url: "https://github.com/proxmox"
                icon: di:proxmox
              - title: Portainer
                url: "https://github.com/portainer/portainer"
                icon: di:portainer
              - title: Keycloak
                url: "https://github.com/keycloak/keycloak"
                icon: di:keycloak
              - title: Semaphore UI
                url: https://github.com/semaphoreui/semaphore
                icon: /assets/icons/semaphore-ui.png
              - title: Kopia
                url: "https://github.com/kopia/kopia"
                icon: di:kopia
              - title: Traefik
                url: "https://github.com/traefik/traefik"
                icon: /assets/icons/traefik.png
              - title: AdGuard Home
                url: "https://github.com/AdguardTeam/AdGuardHome"
                icon: /assets/icons/adguardhome.png