server:
  # https://github.com/glanceapp/glance/blob/main/docs/configuration.md#assets-path
  assets-path: /app/assets

# https://github.com/glanceapp/glance/blob/main/docs/themes.md
theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65

pages:
  - name: Dashboard
    width: slim
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      # Left Column
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
          - type: calendar
            first-day-of-week: sunday
          - type: weather
            location: Fukuoka, Japan

      # Right Column (takes remaining space)
      - size: full
        widgets:
          - type: monitor
            title: Services
            cache: 1m
            sites:
              - title: Nextcloud
                url: https://yourdomain.com/
                icon: si:jellyfin
              - title: Forgejo
                url: https://yourdomain.com/
                icon: si:forgejo
              - title: Vaultwarden
                url: https://yourdomain.com/
                icon: si:vaultwarden
          - type: monitor
            title: Monitoring
            cache: 1m
            sites:
              - title: Beszel
                url: "#"
                icon: /assets/icons/beszel.png
              - title: Dozzle
                url: "https://google.com"
                icon: di:dozzle
              - title: Uptime Kuma
                url: "#"
                icon: si:uptimekuma
          - type: monitor
            title: Server Management
            cache: 1m
            sites:
              - title: Proxmox
                url: "#"
                icon: si:proxmox
              - title: Portainer
                url: "#"
                icon: si:portainer
              - title: Kopia
                url: "#"
                icon: di:kopia
              - title: AdGuard Home
                url: https://yourdomain.com/
                icon: si:adguard