---
ansible_host: 192.168.56.11
ansible_user: dummy
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36393336356335373463313437333934613733393037323735323831626132663862373730323861
          3265323439653637633433386239313533336436623838300a386334316437336538343539626437
          62326639663630643231643835333433386537303336333232636632653232396365623865303162
          6435663363633766320a663131303564336262643937653265316639396537643363393166343931
          3131
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36636661376332353936323732393261343865643835663631396434616362626131333437656636
          3530336436663562613963663336353531363132313334380a643631316232303332386331333864
          39303236643263383864383961653837396435383330303837646162626631373330333933623433
          3933656434393261660a313266653332623433373732336235323430653963646461303665633238
          3230