---
ansible_host: 192.168.56.11
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63316362653037373230373030356261396262386631333938663664333832363661666637336237
          6537633133616534616165356136306434333432333430320a363665393639393332306139663035
          33333939343233323637613537613262666566376536323863393737303361326336313833306636
          3763393363356234350a353439666666323033636666363632376134646339656131306135303538
          3538