name: Visual C++ Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: windows
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64, x86]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
        
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1
        
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: NuGet Restore
        run: nuget restore YourSolution.sln
        
      - name: Build Solution
        run: |
          msbuild /m /p:Configuration=${{ matrix.configuration }} /p:Platform=${{ matrix.platform }} YourSolution.sln
          
      - name: Run Tests
        run: |
          vstest.console.exe /Platform:${{ matrix.platform }} **\bin\${{ matrix.configuration }}\*test*.dll
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}-${{ matrix.configuration }}
          path: |
            **\bin\${{ matrix.configuration }}\*.exe
            **\bin\${{ matrix.configuration }}\*.dll
            !**\bin\${{ matrix.configuration }}\*test*.dll
