---
- name: Manage Ubuntu system updates
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: check-update
      tags: check
    - role: security-upgrade
      tags: security-upgrade
    - role: dist-upgarde
      tags: dist-upgrade
    - role: reboot
      tags: reboot