---
- name: Manage Ubuntu system updates
  hosts: ubuntu_servers
  become: true
  gather_facts: true

  roles:
    - role: check-updates
      tags: check
    - role: security-update
      tags: security
    - role: system-update
      tags: update
    - role: reboot
      tags: reboot