# https://github.com/CorentinTh/it-tools?tab=readme-ov-file#self-host

services:
  it-tools:
    container_name: it-tools
    # https://hub.docker.com/r/corentinth/it-tools/tags
    image: 'corentinth/it-tools:2024.10.22-7ca5933'
    restart: unless-stopped
    # ports:
    #   - '8080:80'
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # Router configuration
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
      - "traefik.http.routers.it-tools-local.rule=Host(`it-tools.yourdomain.local`)"
      - "traefik.http.routers.it-tools-local.entrypoints=websecure"
      - "traefik.http.routers.it-tools-local.tls.certresolver=stepca"

networks:
  proxy:
    external: true
