---
# https://docs.docker.com/engine/install/ubuntu/#uninstall-old-versions
- name: Uninstall unofficial Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Ensure required packages are installed
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present
    update_cache: yes

- name: Ensure directory for Docker keys exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.asc
    state: present

- name: Add Docker repository to apt repository
  block:
    - name: Prepare Docker repository
      ansible.builtin.command: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable"
      register: docker_repo

    - name: Add Docker repository to apt repository
      ansible.builtin.apt_repository:
        repo: "{{ docker_repo.stdout }}"
        state: present

- name: Install Docker Engine packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Install Docker Python module to use Ansible Community Docker collections
  ansible.builtin.pip:
    name: docker
    state: present

- name: Ensure Docker service is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html
- name: Verify Docker installation
  community.docker.docker_container:
    name: hello-world
    image: hello-world
    auto_remove: true
    state: started

- name: Show Docker verification result
  ansible.builtin.debug:
    var: hello_world_result.stdout_lines
  when: hello_world_result is succeeded