# https://tailscale.com/blog/docker-tailscale-guide
# https://tailscale.com/kb/1282/docker#code-examples
# https://gist.github.com/bnhf/fed4cc3035f32a0f086b1da074a3d50b

services:
  tailscale:
    # https://hub.docker.com/r/tailscale/tailscale/tags
    image: tailscale/tailscale:v1.78.3
    container_name: tailscale
    # hostname: Docker-Tailscale
    restart: unless-stopped
    environment:
      # NOTE: parameters: https://tailscale.com/kb/1282/docker#parameters
      TS_AUTHKEY: ${TS_AUTHKEY}
      # TS_EXTRA_ARGS: "--accept-routes --advertise-tags=tag:container --reset"
      TS_EXTRA_ARGS: "--stateful-filtering=false --accept-dns=false --accept-routes --advertise-exit-node --advertise-tags=tag:container --reset"
      TS_STATE_DIR: /var/lib/tailscale
      # NOTE: https://www.reddit.com/r/Tailscale/comments/104y6nq/docker_tailscale_and_caddy_with_https_a_love_story/
      # TS_SOCKET: ${TS_SOCKET}
      TS_ROUTES: ${TS_ROUTES}
      TS_USERSPACE: false
    cap_add:
      - net_admin
      - sys_module
    volumes:
      - tailscale-state:/var/lib/tailscale
      # NOTE: enable access to tun for LXC containers
      # https://tailscale.com/kb/1130/lxc-unprivileged
      # - /dev/net/tun:/dev/net/tun
    # NOTE: latest containerd version >=v1.7.24
    # https://github.com/tailscale/tailscale/issues/14256#issuecomment-2509791148
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      openwrt_vlan:
        ipv4_address: 10.10.10.8

networks:
  openwrt_vlan:
    external: true

volumes:
  tailscale-state:
    driver: local
