---
ansible_host: 192.168.56.11
ansible_user: dummy
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33316631366532643461326631626635633364343966633539646532346464316137616530386535
          6330643466323832366332633764303130346330626636630a316366343764613231666136616363
          39306338393864396265613033373461353436343763316331316436343662313766346236383837
          3431616363393435660a623235346132373733303434663134313831353932353235333137626335
          6537
ansible_become_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63346130613331653162373339383666333533393234643264623330373131373765326263623563
          6536383265346165643562363965383265353662393464640a343233356331653933346362656434
          39613638383065323132323635663233663662383432363465326261383430356239356332656434
          3031373063386662330a633130373435353736313137636466626364643935623566393337396334
          3864

# Nextcloud data and configuration directories
nextcloud_backup_dir: "/home/vagrant/backup/docker/nextcloud"
nextcloud_data_dir: "/home/vagrant/appdata/docker/nextcloud/data"
nextcloud_html_dir: "/home/vagrant/appdata/docker/nextcloud/html"
nextcloud_custom_apps_dir: "/home/vagrant/appdata/docker/nextcloud/custom_apps"
nextcloud_config_dir: "/home/vagrant/appdata/docker/nextcloud/config"
postgres_data_dir: "./postgres"
redis_data_dir: "./redis"

# Kopia variables
use_kopia: true
kopia_backup_data_dir: "/data"
kopia_nextcloud_backup_dir: "{{kopia_backup_data_dir}}/{{ nextcloud_backup_dir }}"

# Nextcloud Secrets (Encrypted)
nextcloud_admin_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66663864386231383234383839343039383037393533393233613537656263303337613366343236
          6664383834376431313938626334363865663331633562370a616633616530613632366363636362
          64353838363930626137366235386561616664386662343934393632633666643262343761386161
          6236353130633161640a323735376433613038393464306633356339383566613931663762653632
          3837
nextcloud_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30346238353233313163313065326631346339396663386133303664653664386535343362343830
          3138323034363533383330343262376236373837353536330a343436346438353061323362633036
          62653830383165363263353766356131633832616537636664653832623862616265343834303130
          3061346463616330610a366136346339616531343038303265393536303630626663666531396434
          3034
nextcloud_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64376238363436366438633737343964623861323566623864366139393065313665626136313734
          3730363134313734373032636631346632366537376162340a613137393731356436636164633736
          63613461343638306431366536393835643132653831366364316237323939633965646662323532
          3263363465333666340a313036326432663436373466663164393762303939653861353332623839
          3632
nextcloud_redis_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62333236303838613839363732656636323634383230373465346132366463363839363437353766
          3966626239643135326565626530306131336239636230630a633763313563323933303664633265
          38386165643536646161326635666435343262666561333861336464626530346433326365323761
          3266303131343532620a313733343538616538633265663464656662383461313864343963663638
          36383632303866613637393837613131633930623530303933653132366137383632
nextcloud_whiteboard_jwt_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31386366343933373166356461623966313234306663363736626430336330333338343762626333
          3262393639626338333335323061303565366261363734340a353337323939396239353930663934
          61336635306164623530636265613263353638376237383964366439366339353663666633316562
          6239313164373630630a643063646431633632336431663336653832343666383539613438663330
          31346139326134633539333539313433373339623763303737366464376365323466383666346233
          3735616339323538353836343866623263663138353832303538
collabora_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65663164376563356363393733383630393166323266353433353761303964613936323438623239
          3334396433363334356539323338346562373562326632640a353664636635316334313038383363
          66393138363635376365393465613063613562613065376531633664383665616139623332333433
          3938623564613237320a636163306366323031633430336130633632653764323232303432323134
          3138
collabora_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37616637316330363066393736356665613633636337633863396237396662386536313661396538
          3361356634663332303630613861626530396339373464320a313338323237356363633836396362
          39313831346163653236313337336661336636623134313430356132326465333666326566663436
          6161383831653532390a626632616263303530643433333834663730613538313534643335646361
          63626565333538633535613262613566646161306362653962343062303931353531643834623263
          3033323061663938313362663836353835373639383335343462