# https://dozzle.dev/guide/getting-started#running-with-docker

services:
  dozzle:
    container_name: dozzle
    # https://hub.docker.com/r/amir20/dozzle/tags
    image: amir20/dozzle:v8.7.2
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle-local.rule=Host(`dozzle.yourdomain.local`)"
      - "traefik.http.routers.dozzle-local.entrypoints=websecure"
      - "traefik.http.routers.dozzle-local.tls=true"
      - "traefik.http.routers.dozzle-local.tls.certresolver=stepca"
      - "traefik.http.routers.dozzle-local.middlewares=oauth2-admin@file"

networks:
  proxy:
    external: true
