# https://github.com/heyvaldemar/keycloak-traefik-letsencrypt-docker-compose
# https://www.keycloak.org/server/containers
# https://medium.com/@disa2aka/docker-deployments-for-keycloak-and-postgresql-e75707b155e5
#
# NOTE: CPU does not support x86-64-v2 error on Proxmox VM
# https://github.com/keycloak/keycloak/issues/17290

services:
  keycloak-postgres:
    # https://hub.docker.com/_/postgres/tags
    image: postgres:16.5-alpine3.20
    container_name: keycloak-postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
    networks:
      - keycloak
    secrets:
      - db_password
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${KEYCLOAK_DB_NAME}", "-U", "${KEYCLOAK_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  keycloak:
    # https://quay.io/repository/keycloak/keycloak?tab=tags
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: keycloak
    restart: unless-stopped
    command: start
    # NOTE: how to use docker secrets
    # https://github.com/keycloak/keycloak/issues/10816
    # entrypoint:
    #   - /bin/bash
    #   - -c
    #   - |
    #     export KC_DB_USERNAME=$$(cat /run/secrets/keycloak_db_uname)
    #     export KC_DB_PASSWORD=$$(cat /run/secrets/keycloak_db_pwd)
    #     export KC_DB_URL=$$(cat /run/secrets/keycloak_db_url)
    #     export KEYCLOAK_ADMIN=$$(cat /run/secrets/keycloak_admin)
    #     export KEYCLOAK_ADMIN_PASSWORD=$$(cat /run/secrets/db_password)
    #     /opt/keycloak/bin/kc.sh start
    #
    # NOTE: keycloak all configuration
    # https://www.keycloak.org/server/all-config
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      # NOTE: hostname configuration
      # https://www.keycloak.org/server/hostname#_validations
      # Disable Keycloak hostname because we are using Traefik as reverse proxy to manage the hostname
      KC_HOSTNAME_STRICT: false
      # KC_HOSTNAME: localhost
      # NOTE: https configuration
      # https://www.keycloak.org/server/enabletls
      KC_HTTP_ENABLED: true
      # KC_HOSTNAME_PORT: 8443
      # NOTE: reverse proxy configuration
      # https://www.keycloak.org/server/reverseproxy
      KC_PROXY_HEADERS: 'xforwarded'

      # NOTE: logging
      # https://www.keycloak.org/server/logging
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
    # volumes:
    #   # https://smallstep.com/docs/tutorials/keycloak-oidc-provisioner/#install-and-run-keycloak--mysql-using-docker-compose
    #   - /path/to/step-ca/certs:/etc/x509/https:ro
    # NOTE: keycloak default ports
    # 8443: https admin console
    # 8080: http admin console "KC_HTTP_ENABLED: true"
    # 9000: https health check
    # ports:
    #   - "8443:8443"
    #   - "9000:9000"
    depends_on:
      - keycloak-postgres
    networks:
      - keycloak
      - proxy
    # https://gist.github.com/sarath-soman/5d9aec06953bbd0990c648605d4dba07?permalink_comment_id=5225953#gistcomment-5225953
    healthcheck:
      test:
        - "CMD-SHELL"
        - |
          exec 3<>/dev/tcp/127.0.0.1/9000 &&
          echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 &&
          cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      # NOTE: specific docker network for Traefik to use
      # https://doc.traefik.io/traefik/providers/docker/#network
      - "traefik.docker.network=proxy"
      - "traefik.http.services.keycloak-local.loadbalancer.server.port=8080"
      - "traefik.http.routers.keyloak-local.entrypoints=websecure"
      - "traefik.http.routers.keyloak-local.rule=Host(`keycloak.yourdomain.local`)"
      - "traefik.http.routers.keyloak-local.tls.certresolver=stepca"

secrets:
  db_password:
    file: ./secrets/db_password

networks:
  proxy:
    external: true
  keycloak:
    driver: bridge
